packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.5
  '@cloudflare/workers-types': ^4.20251121.0
  '@opennextjs/cloudflare': ^1.12.0
  '@orpc/server': 1.11.3
  "@orpc/client": ^1.11.3
  '@types/node': ^24.10.1
  '@types/react': ^19.2.5
  '@types/react-dom': ^19.2.3
  hono: ^4.10.6
  next: ^15.5.6
  react: ^19.2.0
  react-dom: ^19.2.0
  typescript: ^5.9.3
  zod: ^4.1.12
  '@orpc/tanstack-query': ^1.11.3
  '@tanstack/react-query': ^5.90.10
  '@tailwindcss/postcss': ^4.1.17
  'postcss': ^8.5.6
  'tailwindcss': ^4.1.17
  'alchemy': ^0.77.5
  "lucide-react": ^0.554.0
