packages:
  - apps/*
  - packages/*

catalog:
  '@biomejs/biome': ^2.3.5
  '@cloudflare/workers-types': ^4.20251121.0
  '@opennextjs/cloudflare': ^1.12.0
  '@orpc/client': ^1.11.3
  '@orpc/server': 1.11.3
  '@orpc/tanstack-query': ^1.11.3
  '@tailwindcss/postcss': ^4.1.17
  '@tanstack/react-query': ^5.90.10
  '@types/node': 24.10.1
  '@types/react': ^19.2.5
  '@types/react-dom': ^19.2.3
  alchemy: ^0.77.5
  hono: ^4.10.6
  lucide-react: ^0.554.0
  next: ^15.5.6
  postcss: ^8.5.6
  react: ^19.2.0
  react-dom: ^19.2.0
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  zod: ^4.1.12
  drizzle-kit: ^0.31.7
  drizzle-orm: ^0.44.7
